// Code generated by protoc-gen-go. DO NOT EDIT.
// source: julian.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConvertRequest struct {
	// Date and time to convert
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour                 float64  `protobuf:"fixed64,4,opt,name=hour,proto3" json:"hour,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertRequest) Reset()         { *m = ConvertRequest{} }
func (m *ConvertRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertRequest) ProtoMessage()    {}
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_838069e7f4e90ff2, []int{0}
}

func (m *ConvertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRequest.Unmarshal(m, b)
}
func (m *ConvertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRequest.Marshal(b, m, deterministic)
}
func (m *ConvertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRequest.Merge(m, src)
}
func (m *ConvertRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertRequest.Size(m)
}
func (m *ConvertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRequest proto.InternalMessageInfo

func (m *ConvertRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *ConvertRequest) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *ConvertRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *ConvertRequest) GetHour() float64 {
	if m != nil {
		return m.Hour
	}
	return 0
}

type JulianResponse struct {
	JulianDateTime       float64  `protobuf:"fixed64,1,opt,name=julianDateTime,proto3" json:"julianDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JulianResponse) Reset()         { *m = JulianResponse{} }
func (m *JulianResponse) String() string { return proto.CompactTextString(m) }
func (*JulianResponse) ProtoMessage()    {}
func (*JulianResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_838069e7f4e90ff2, []int{1}
}

func (m *JulianResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JulianResponse.Unmarshal(m, b)
}
func (m *JulianResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JulianResponse.Marshal(b, m, deterministic)
}
func (m *JulianResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JulianResponse.Merge(m, src)
}
func (m *JulianResponse) XXX_Size() int {
	return xxx_messageInfo_JulianResponse.Size(m)
}
func (m *JulianResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JulianResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JulianResponse proto.InternalMessageInfo

func (m *JulianResponse) GetJulianDateTime() float64 {
	if m != nil {
		return m.JulianDateTime
	}
	return 0
}

type JulianRequest struct {
	JulianDateTime       float64  `protobuf:"fixed64,1,opt,name=julianDateTime,proto3" json:"julianDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JulianRequest) Reset()         { *m = JulianRequest{} }
func (m *JulianRequest) String() string { return proto.CompactTextString(m) }
func (*JulianRequest) ProtoMessage()    {}
func (*JulianRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_838069e7f4e90ff2, []int{2}
}

func (m *JulianRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JulianRequest.Unmarshal(m, b)
}
func (m *JulianRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JulianRequest.Marshal(b, m, deterministic)
}
func (m *JulianRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JulianRequest.Merge(m, src)
}
func (m *JulianRequest) XXX_Size() int {
	return xxx_messageInfo_JulianRequest.Size(m)
}
func (m *JulianRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JulianRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JulianRequest proto.InternalMessageInfo

func (m *JulianRequest) GetJulianDateTime() float64 {
	if m != nil {
		return m.JulianDateTime
	}
	return 0
}

type CalendarResponse struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalendarResponse) Reset()         { *m = CalendarResponse{} }
func (m *CalendarResponse) String() string { return proto.CompactTextString(m) }
func (*CalendarResponse) ProtoMessage()    {}
func (*CalendarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_838069e7f4e90ff2, []int{3}
}

func (m *CalendarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalendarResponse.Unmarshal(m, b)
}
func (m *CalendarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalendarResponse.Marshal(b, m, deterministic)
}
func (m *CalendarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalendarResponse.Merge(m, src)
}
func (m *CalendarResponse) XXX_Size() int {
	return xxx_messageInfo_CalendarResponse.Size(m)
}
func (m *CalendarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalendarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalendarResponse proto.InternalMessageInfo

func (m *CalendarResponse) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *CalendarResponse) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *CalendarResponse) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func init() {
	proto.RegisterType((*ConvertRequest)(nil), "v1.ConvertRequest")
	proto.RegisterType((*JulianResponse)(nil), "v1.JulianResponse")
	proto.RegisterType((*JulianRequest)(nil), "v1.JulianRequest")
	proto.RegisterType((*CalendarResponse)(nil), "v1.CalendarResponse")
}

func init() { proto.RegisterFile("julian.proto", fileDescriptor_838069e7f4e90ff2) }

var fileDescriptor_838069e7f4e90ff2 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0xb4, 0x55, 0x18, 0x34, 0xa4, 0x43, 0x0f, 0xa1, 0xa7, 0x92, 0x83, 0xf4, 0x14,
	0x88, 0x1e, 0x14, 0x3d, 0xa6, 0x78, 0xe8, 0xc1, 0xc3, 0xea, 0x0f, 0x70, 0xb5, 0x03, 0x8d, 0x34,
	0xbb, 0x75, 0xb3, 0x09, 0xe4, 0xe6, 0x4f, 0x97, 0xcc, 0xb6, 0x62, 0x83, 0x82, 0xd8, 0xdb, 0xec,
	0x63, 0xbf, 0x9d, 0xf7, 0x1e, 0x0b, 0x67, 0x6f, 0xf5, 0xa6, 0x50, 0x3a, 0xdd, 0x5a, 0xe3, 0x0c,
	0x06, 0x4d, 0x96, 0x3c, 0x43, 0x98, 0x1b, 0xdd, 0x90, 0x75, 0x92, 0xde, 0x6b, 0xaa, 0x1c, 0x22,
	0x0c, 0x5b, 0x52, 0x36, 0x16, 0x33, 0x31, 0x1f, 0x49, 0x9e, 0x71, 0x02, 0xa3, 0xd2, 0x68, 0xb7,
	0x8e, 0x03, 0x16, 0xfd, 0x01, 0x23, 0x18, 0xac, 0x54, 0x1b, 0x0f, 0x58, 0xeb, 0xc6, 0x8e, 0x5d,
	0x9b, 0xda, 0xc6, 0xc3, 0x99, 0x98, 0x0b, 0xc9, 0x73, 0x72, 0x03, 0xe1, 0x92, 0xb7, 0x4a, 0xaa,
	0xb6, 0x46, 0x57, 0x84, 0x17, 0x10, 0x7a, 0x1f, 0x0b, 0xe5, 0xe8, 0xa9, 0x28, 0x89, 0x77, 0x09,
	0xd9, 0x53, 0x93, 0x6b, 0x38, 0xdf, 0x93, 0xde, 0xda, 0x5f, 0xc1, 0x07, 0x88, 0x72, 0xb5, 0x21,
	0xbd, 0x52, 0xf6, 0x6b, 0xe9, 0x11, 0xb1, 0x2e, 0x3f, 0x82, 0xbd, 0x93, 0x47, 0xb2, 0x4d, 0xf1,
	0x4a, 0x98, 0xc1, 0xe9, 0xae, 0x36, 0xc4, 0xb4, 0xc9, 0xd2, 0xc3, 0x0e, 0xa7, 0xac, 0xf5, 0x52,
	0xdf, 0xc2, 0xb8, 0x33, 0xe7, 0xd5, 0x9c, 0xb4, 0xab, 0x6d, 0x8b, 0xe3, 0xef, 0x17, 0x7f, 0x67,
	0x73, 0x98, 0x2e, 0x77, 0x11, 0xdb, 0x7b, 0x6b, 0xca, 0x7f, 0x3d, 0x72, 0x07, 0xd1, 0x01, 0xbe,
	0x50, 0x3f, 0xa2, 0x13, 0xce, 0xd3, 0xab, 0xef, 0xe5, 0x84, 0xbf, 0xcc, 0xd5, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x64, 0x73, 0x88, 0xab, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JulianServiceClient is the client API for JulianService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JulianServiceClient interface {
	// Convert to Julian date
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*JulianResponse, error)
	TimeJulianCentury(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*JulianResponse, error)
	JulianDayFromJulianCentury(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*JulianResponse, error)
	DayFromJulianDay(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*CalendarResponse, error)
}

type julianServiceClient struct {
	cc *grpc.ClientConn
}

func NewJulianServiceClient(cc *grpc.ClientConn) JulianServiceClient {
	return &julianServiceClient{cc}
}

func (c *julianServiceClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*JulianResponse, error) {
	out := new(JulianResponse)
	err := c.cc.Invoke(ctx, "/v1.JulianService/Convert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *julianServiceClient) TimeJulianCentury(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*JulianResponse, error) {
	out := new(JulianResponse)
	err := c.cc.Invoke(ctx, "/v1.JulianService/TimeJulianCentury", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *julianServiceClient) JulianDayFromJulianCentury(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*JulianResponse, error) {
	out := new(JulianResponse)
	err := c.cc.Invoke(ctx, "/v1.JulianService/JulianDayFromJulianCentury", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *julianServiceClient) DayFromJulianDay(ctx context.Context, in *JulianRequest, opts ...grpc.CallOption) (*CalendarResponse, error) {
	out := new(CalendarResponse)
	err := c.cc.Invoke(ctx, "/v1.JulianService/DayFromJulianDay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JulianServiceServer is the server API for JulianService service.
type JulianServiceServer interface {
	// Convert to Julian date
	Convert(context.Context, *ConvertRequest) (*JulianResponse, error)
	TimeJulianCentury(context.Context, *JulianRequest) (*JulianResponse, error)
	JulianDayFromJulianCentury(context.Context, *JulianRequest) (*JulianResponse, error)
	DayFromJulianDay(context.Context, *JulianRequest) (*CalendarResponse, error)
}

func RegisterJulianServiceServer(s *grpc.Server, srv JulianServiceServer) {
	s.RegisterService(&_JulianService_serviceDesc, srv)
}

func _JulianService_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JulianServiceServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.JulianService/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JulianServiceServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JulianService_TimeJulianCentury_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JulianRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JulianServiceServer).TimeJulianCentury(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.JulianService/TimeJulianCentury",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JulianServiceServer).TimeJulianCentury(ctx, req.(*JulianRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JulianService_JulianDayFromJulianCentury_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JulianRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JulianServiceServer).JulianDayFromJulianCentury(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.JulianService/JulianDayFromJulianCentury",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JulianServiceServer).JulianDayFromJulianCentury(ctx, req.(*JulianRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JulianService_DayFromJulianDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JulianRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JulianServiceServer).DayFromJulianDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.JulianService/DayFromJulianDay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JulianServiceServer).DayFromJulianDay(ctx, req.(*JulianRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JulianService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.JulianService",
	HandlerType: (*JulianServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Convert",
			Handler:    _JulianService_Convert_Handler,
		},
		{
			MethodName: "TimeJulianCentury",
			Handler:    _JulianService_TimeJulianCentury_Handler,
		},
		{
			MethodName: "JulianDayFromJulianCentury",
			Handler:    _JulianService_JulianDayFromJulianCentury_Handler,
		},
		{
			MethodName: "DayFromJulianDay",
			Handler:    _JulianService_DayFromJulianDay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "julian.proto",
}
